package cn.camera.safe.api;

public enum ErrorCode {
    INVALID_REQUEST,
    INVALID_COORDINATE,
    UNSUPPORTED_COORDINATE_SYSTEM,
    OUTSIDE_ROUTING_BOUNDS,
    START_IN_RESTRICTED_AREA,
    END_IN_RESTRICTED_AREA,
    NO_COMPLIANT_ROUTE,
    ROUTE_CONFLICT_DETECTED,
    ROUTING_NOT_READY,
    CAMERA_SNAPSHOT_NOT_READY,
    REFRESH_ALREADY_RUNNING,
    INTERNAL_ERROR
}
